version: '3'

services:
  frontend:
    container_name: frontend
    image: frontend:custom
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend


  backend:
    container_name: backend
    image: backend:custom
    build: ./backend
    restart: unless-stopped
    ports:
      - '8000:8000'
      