services:
  db:
    container_name: postgres
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: frontend:custom
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    container_name: backend
    image: backend:custom
    build: ./backend
    restart: unless-stopped
    ports:
      - '8000:8000'

volumes:
  postgres:
      