services:
  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: frontend:custom
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    container_name: backend
    image: backend:custom
    build: ./backend
    restart: unless-stopped
    volumes:
      - backend_media:/app/backend/media
    ports:
      - '8000:8000'
    depends_on:
      - postgres
  
  redis:
    container_name: redis
    image: redis:7
    ports:
      - '6379:6379'
  
  celery:
    container_name: celery
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - backend_media:/app/backend/media
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  postgres:
  backend_media:
      